### ISSUE TITLE
cannot test against local instance because of various host/protocol/etc handling

### ISSUE THREAD

**Issue by FoxLisk** [fenhl/rust-racetime#1]
This method just has `https` hardcoded, which isn't great for testing this locally:

https://github.com/fenhl/rust-racetime/blob/main/src/lib.rs#L77

It doesn't appear to be possible to specify a port to run on because of this line:

`let (ws_conn, _) = tokio_tungstenite::client_async_tls(request, TcpStream::connect((&*data.host, 443)).await?).await?;`

(https://github.com/fenhl/rust-racetime/blob/main/src/bot.rs#L162)

which requires both that `data.host` is just a hostname, and that we are using port 443

I'm sure I'll run into more (I see a `wss://` hardcoded somewhere).

Would you be interested if I put together a patch for this?

**Comment by fenhl** [comment]
A PR would very much be appreciated! Honestly it simply never occurred to me that you would want to test locally.

**Comment by FoxLisk** [comment]
Haha, the RT.gg documentation recommends testing locally, so I was just following their suggestions. I'll put up a PR in a couple days probably. Thanks!

**Comment by fenhl** [comment]
Implemented in #2.
